config/routes.rb
Rails.application.routes.draw do
  get "/" => "users#top"
  get "/users/log_in" => "users#login_form"
  post "/users/log_in" => "users#login"
  post "/users/log_out" => "users#logout"
  get "/users/sign_up" => "users#signup_form"
  get "/users/account" => "users#account"
  patch "/users/:id/edit" => "users#update_account"
  get "/users/profile" => "users#profile"
  patch "/users/profile" => "users#update_profile"

  get "/rooms/posts" => "rooms#rooms"
  get "/search-area" => "rooms#search_area"
  get "/search-keyword" => "rooms#search_keyword"

  get "/reservations" => "reservations#reservations"
  post "/rooms/:id" => "reservations#confirm"
  post "/rooms/:id/confirm" => "reservations#create"

  resources :rooms
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :start_date, date_before: true
  validates :end_date, date_before: true
  validates :people, presence: true, numericality: true

  belongs_to :user, optional: true
  belongs_to :room, optional: true
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :introduction, presence: true, length: {maximum: 100}
  validates :price, presence: true, numericality: true
  validates :address, presence: true, length: {maximum: 30}
  validates :image, presence: true

  belongs_to :user, optional: true
  has_many :reservations, dependent: :destroy

  mount_uploader :image, RoomUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create
  validates :password_reset, confirmation: true
  validates :introduction, length: {maximum: 50}

  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy

  mount_uploader :icon, IconUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインしてください"
      redirect_to("/users/log_in")
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to("/")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user, {
    only: [
      :reservations,
      :confirm,
      :create
    ]
  }

  def reservations
    @reservations = Reservation.where(user_id: session[:user_id])
  end

  def confirm
    @reservation = Reservation.new(params.require(:reservation).permit(:start_date, :end_date, :people, :room_id))
    @user = User.find(session[:user_id])
    @room = Room.find(@reservation.room_id)
    if @reservation.valid?
      if (@reservation.end_date - @reservation.start_date).to_i < 1
        @reservation.errors.add(:end_date, "は開始日より後にしてください")
        @room = Room.find(params[:id])
        @user = User.find(@room.user_id)
        render("rooms/show")
      else
        @reservation.user_id = @user.id
        @reservation.room_image = @room.image
        @reservation.room_name = @room.name
        @reservation.room_introduction = @room.introduction
        @reservation.room_total_price = @room.price * @reservation.people * (@reservation.end_date - @reservation.start_date).to_i
      end
    else
      @room = Room.find(params[:id])
      @user = User.find(@room.user_id)
      render("rooms/show")
    end
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:room_id, :user_id, :start_date, :end_date, :people, :room_image, :room_name, :room_introduction, :room_total_price))
    if @reservation.save
      flash[:notice] = "予約されました"
      redirect_to "/reservations"
    else
      flash[:notice] = "もう一度やり直してください"
      redirect_to "/"
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user, {
    only: [
      :new,
      :create,
      :posts,
      :edit,
      :update,
      :destroy
    ]
  }

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :introduction, :price, :address, :image))
    @room.user_id = session[:user_id]
    if @room.save
      flash[:notice] = "ルームを登録しました"
      redirect_to "/rooms/posts"
    else
      render("new")
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = User.find(@room.user_id)
    @reservation = Reservation.new
  end

  def rooms
    @rooms = Room.where(user_id: session[:user_id])
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(params.require(:room).permit(:name, :introduction, :price, :address, :image))
      flash[:notice] = "ルーム情報を更新しました"
      redirect_to("/rooms/posts")
    else
      render("edit")
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "削除しました"
    redirect_to("/rooms/posts")
  end

  def search_area
    if params[:search].present?
      @rooms = Room.where("address LIKE ?", "%#{params[:search]}%")
    else
      @rooms = Room.all
    end
    @count = @rooms.count
    render "index"
  end

  def search_keyword
    if params[:search].present?
      @rooms = Room.where("name LIKE ? OR introduction LIKE ? OR address LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @rooms = Room.all
    end
    @count = @rooms.count
    render "index"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {
    only: [
    :logout,
    :account,
    :profile,
    :edit,
    :update_profile,
    :update_account,
    :destroy
    ]
  }
  before_action :forbid_login_user, {
    only: [
    :login_form,
    :login,
    :signup_form,
    :create,
    ]
  }

  def top
  end

  def login_form
    @user = User.new
  end

  def login
    @user = User.find_by(
      email: params[:email],
      password: params[:password]
    )
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      @input = params[:email]
      @error_message = "メールアドレス もしくはパスワードが不正です"
      render "login_form"
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/users/log_in")
  end

  def signup_form
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録しました"
      redirect_to("/")
    else
      render "signup_form"
    end
  end

  def account
    @user = User.find(session[:user_id])
  end

  def profile
    @user = User.find(session[:user_id])
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update_profile
    @user = User.find(session[:user_id])
    if @user.update(params.require(:user).permit(:icon, :name, :introduction))
      flash[:notice] = "プロフィール情報を更新しました"
      redirect_to :users_profile
    else
      render "profile"
    end
  end

  def update_account
    @user = User.find(session[:user_id])
    @user_update = User.new(params.require(:user).permit(:email, :password, :password_reset, :password_reset_confirmation))
    if @user.password == @user_update.password
      if @user.update(params.require(:user).permit(:email, :password, :password_reset, :password_reset_confirmation))
        unless @user.password_reset.empty?
          @user.password = @user.password_reset
          @user.save
        end
        flash[:notice] = "アカウント情報を更新しました"
        redirect_to("/users/account")
      else
        render "edit"
      end
    else
      @error_message = "パスワードが間違っています"
      render "edit"
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "退会しました"
    redirect_to("/")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelReserve</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="header">
        <div class="header-left">
          <%= link_to "HotelReserve", "/", class: "header-logo" %>
          <div class="header-search">
            <i class="fa fa-map-marker icon" aria-hidden="true"></i>
            <%= form_with url: search_area_path, method: :get do |f|%>
              <%= f.text_field "search", class: "header-search-field", :placeholder => "エリア" %>
            <%end%>
          </div>
          <div class="header-search">
            <i class="fa fa-search icon" aria-hidden="true"></i>
            <%= form_with url: search_keyword_path, method: :get do |f|%>
              <%= f.text_field "search", class: "header-search-field", :placeholder => "キーワード" %>
            <%end%>
          </div>
        </div>

        <div class="header-right">
          <% if @current_user %>
            <div class="header-profile">
              <p class="header-profile-name"><%= @current_user.name %></p>
              <%= image_tag "#{@current_user.icon}" , class: "header-profile-image" %>
            </div>
          <% else %>
            <%= link_to "ログイン", "/users/log_in", class: "header-login button" %>
            <%= link_to "登録する", "/users/sign_up", class: "header-signup button" %>
          <% end %>
        </div>
      </div>
    </header>

    <div class="header-background">
    </div>

    <div class="header-menu display-none">
      <ul>
        <li class="header-menu-text"><%= link_to "ルーム登録", :new_room %></li>
        <li class="header-menu-text"><%= link_to "予約済みルーム一覧", "/reservations"%></li>
        <li class="header-menu-text"><%= link_to "登録済みルーム一覧", "/rooms/posts"%></li>
        <li class="header-menu-text"><%= link_to "設定", "/users/account"%></li>
        <li class="header-menu-text"><%= link_to "ログアウト", "/users/log_out", method: :post %></li>
      </ul>
    </div>

    <% if flash.notice %>
      <p class="flash"><%= flash[:notice] %></p>
    <% end %>

    <%= yield %>

    <footer>
      <div class="footer">
        <p>© 2020 POTEPAN.INC.</p>
      </div>
    </footer>
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="reservation-confirm-wrapper">
  <%= form_with model: @reservation, url: {controller: 'reservations', action: 'create' } do |f| %>
    <%= f.hidden_field :room_id, :value => @reservation.room_id %>
    <%= f.hidden_field :user_id, :value => @reservation.user_id %>
    <%= f.hidden_field :start_date, :value => @reservation.start_date %>
    <%= f.hidden_field :end_date, :value => @reservation.end_date %>
    <%= f.hidden_field :people, :value => @reservation.people %>
    <%= f.hidden_field :room_image, :value => @reservation.room_image %>
    <%= f.hidden_field :room_name, :value => @reservation.room_name %>
    <%= f.hidden_field :room_introduction, :value => @reservation.room_introduction %>
    <%= f.hidden_field :room_total_price, :value => @reservation.room_total_price %>

    <div class="reservation-confirm-box">
      <p class="reservation-confirm-box-title">予約内容確認</p>
      <p class="reservation-confirm-box-price">¥ <%= @room.price %> / 日</p>
      <p class="reservation-confirm-box-frame-title">開始日</p>
      <p class="reservation-confirm-box-frame"><%= @reservation.start_date %></p>
      <p class="reservation-confirm-box-frame-title">終了日</p>
      <p class="reservation-confirm-box-frame"><%= @reservation.end_date %></p>
      <p class="reservation-confirm-box-text">
        使用日数 :
        <%= (@reservation.end_date - @reservation.start_date).to_i %>泊<%= (@reservation.end_date - @reservation.start_date).to_i + 1 %>日
      </p>
      <p class="reservation-confirm-box-text">人数 : <%= @reservation.people %>人</p>
      <p class="reservation-confirm-box-frame-title">合計金額</p>
      <p class="reservation-confirm-box-frame"><%= @reservation.room_total_price %></p>
      <p class="reservation-confirm-box-confirm">上記内容でよろしければ「予約を確定」を押してください</p>
      <div class="reservation-confirm-box-links">
        <%= f.submit "予約を確定",class: "reservation-confirm-box-link-1" %>
        <%= link_to "ルーム詳細に戻る", "/rooms/#{@reservation.room_id}", class: "reservation-confirm-box-link-2" %>
      </div>
    </div>
  <% end %>
</div>

app/views/reservations/reservations.erb
<div class="reservations-wrapper">
  <p class="reservations-title">予約済みルーム一覧</p>
  <div class="reservations-contents">
    <p class="reservations-image">ルーム画像</p>
    <p class="reservations-room-name">ルーム名</p>
    <p class="reservations-room-introduction">ルーム紹介</p>
    <p class="reservations-room-total-price">合計料金</p>
    <p class="reservations-start-date">開始日</p>
    <p class="reservations-end-date">終了日	</p>
    <p class="reservations-update-date">予約確定日時</p>
  </div>
  <% @reservations.each do |f| %>
    <%= link_to "/rooms/#{f.room_id}" do %>
      <div class="reservations-contents">
        <div class="reservations-image">
          <%= image_tag "#{f.room_image}", class: "reservations-image-image" %>
        </div>
        <p class="reservations-room-name"><%= f.room_name %></p>
        <p class="reservations-room-introduction"><%= f.room_introduction %></p>
        <p class="reservations-room-total-price"><%= f.room_total_price %></p>
        <p class="reservations-start-date"><%= f.start_date %></p>
        <p class="reservations-end-date"><%= f.end_date %></p>
        <p class="reservations-update-date"><%= f.updated_at.to_s(:datetime_jp) %></p>
      </div>
      <% end %>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<div class="room-edit-wrapper">
  <div class="side-menu">
    <%= link_to "ルーム情報編集", "/rooms/#{@room.id}/edit", class: "side-menu-text side-menu-blue" %>
  </div>
  <div class="room-edit-box">
    <% if @room.errors.full_messages %>
      <% @room.errors.full_messages.each do |message| %>
        <p class="error"><%= message %></p>
      <% end %>
    <% end %>

    <%= form_with model: @room do |f|%>
      <p class="box-title">ルーム情報編集</p>

      <div class="box-line">
        <%= image_tag "#{@room.image}", class: "room-edit-image" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>ルーム画像</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.file_field :image, class: "room-field" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>ルーム名</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.text_field :name, class: "room-field", :placeholder => "ルーム名を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>ルーム紹介</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.text_area :introduction, class: "room-area", :placeholder => "ルーム説明を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>料金</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.number_field :price, class: "room-field", :placeholder => "一日あたりの料金を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>住所</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.text_field :address, class: "room-field", :placeholder => "住所を入力" %>
      </div>

      <%= f.submit "登録",class: "room-button" %>

    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="room-index-wrapper">
  <% if @count.present?%>
    <p class="room-index-result">検索結果：<%= @count %>件</p>
  <% end %>

  <div class="room-index-list">
    <% @rooms.each do |f| %>
      <%= link_to "/rooms/#{f.id}", class: "room-index-box" do %>
        <div class="room-index-box-inner"></div>
        <div class="room-index-box-contents">
          <%= image_tag "#{f.image}", class: "room-index-image" %>
          <ul class="room-index-texts">
            <li class="room-index-name"><%= f.name %></li>
            <li class="room-index-address"><%= f.address %></li>
            <li class="room-index-price"><%= "¥ #{f.price}" %></li>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="room-new-wrapper">
  <div class="side-menu">
    <%= link_to "基本情報", "/rooms/new", class: "side-menu-text side-menu-blue" %>
  </div>
  <div class="room-new-box">
    <% if @room.errors.full_messages %>
      <% @room.errors.full_messages.each do |message| %>
        <p class="error"><%= message %></p>
      <% end %>
    <% end %>

    <%= form_with model: @room do |f|%>
      <p class="box-title">ルーム情報登録</p>

      <div class="box-line">
        <div class="box-line-text">
          <p>ルーム名</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.text_field :name, class: "room-field", :placeholder => "ルーム名を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>ルーム紹介</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.text_area :introduction, class: "room-area", :placeholder => "ルーム説明を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>料金</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.number_field :price, class: "room-field", :placeholder => "一日あたりの料金を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>住所</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.text_field :address, class: "room-field", :placeholder => "住所を入力" %>
      </div>

      <div class="box-line">
        <div class="box-line-text">
          <p>ルーム画像</p>
          <p class="require-text">必須</p>
        </div>
        <%= f.file_field :image, class: "room-field" %>
      </div>

      <%= f.submit "登録",class: "room-button" %>

    <% end %>
  </div>
</div>

app/views/rooms/rooms.html.erb
<div class="room-posts-wrapper">
  <p class="room-posts-title">登録済みルーム一覧</p>
  <div class="room-posts-contents">
    <p class="room-posts-image">ルーム画像</p>
    <p class="room-posts-name">ルーム名</p>
    <p class="room-posts-introduction">ルーム紹介</p>
    <p class="room-posts-price">料金</p>
    <p class="room-posts-create-date">作成日</p>
    <div class="room-posts-links">
      <p class="room-posts-create-edit"></p>
      <p class="room-posts-create-delete"></p>
    </div>
  </div>

  <% @rooms.each do |f| %>
    <div class="room-posts-contents">
      <div class="room-posts-image">
        <%= image_tag "#{f.image}", class: "room-posts-image-image" %>
      </div>
      <p class="room-posts-name"><%= f.name %></p>
      <p class="room-posts-introduction"><%= f.introduction %></p>
      <p class="room-posts-price"><%= f.price %></p>
      <p class="room-posts-create-date"><%= f.created_at.to_s(:datetime_jp) %></p>
      <div class="room-posts-links">
        <%= link_to "編集", "/rooms/#{f.id}/edit", class: "room-posts-create-edit" %>
        <%= link_to "削除", "/rooms/#{f.id}", method: :delete, data:{confirm: "本当に削除しますか？"}, class: "room-posts-create-delete" %>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="room-show-wrapper">
  <div class="room-show-contents">
    <%= image_tag "#{@room.image}", class: "room-show-image" %>
    <div class="room-show-title">
      <div class="room-show-overview">
        <p class="room-show-name"><%= @room.name %></p>
        <p class="room-show-address"><%= @room.address %></p>
      </div>
      <div class="room-show-owner">
        <%= image_tag "#{@user.icon}" , class: "room-show-owner-image" %>
        <p class="room-show-owner-name"><%= @user.name %></p>
      </div>
    </div>
    <p class="room-show-introduction"><%= @room.introduction %></p>
  </div>

  <div class="room-show-reserve">
    <% if @reservation.errors.full_messages %>
      <% @reservation.errors.full_messages.each do |message| %>
        <p class="error"><%= message %></p>
      <% end %>
    <% end %>

    <div class="room-show-reserve-box">
      <p class="room-show-reserve-price"><%= "¥ #{@room.price} / 日" %></p>
      <%= form_with model: @reservation, url: {controller: 'reservations', action: 'confirm' } do |f| %>
        <ul class="room-show-reserve-form">
          <li>
            <p>開始日</p>
            <%= f.date_field :start_date, class: "reserve-field" %>
          </li>
          <li>
            <p>終了日</p>
            <%= f.date_field :end_date, class: "reserve-field" %>
          </li>
          <li>
            <p>人数</p>
            <%= f.number_field :people, class: "reserve-field" %>
          </li>
        </ul>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <%= f.submit "予約する",class: "reserve-submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/account.html.erb
<div class="account-wrapper">
  <div class="side-menu">
    <%= link_to "アカウント", "/users/account", class: "side-menu-text side-menu-blue" %>
    <%= link_to "プロフィール", "/users/profile", class: "side-menu-text" %>
  </div>
  <div class="account-box">
    <p class="box-title">アカウント</p>
    <div class="box-line">
      <p>メールアドレス</p>
      <p><%= @current_user.email %></p>
    </div>
    <div class="box-line">
      <p>パスワード</p>
      <p>********</p>
    </div>
    <%= link_to "編集" ,"/users/#{@current_user.id}/edit", class: "account-button" %>
    <%= link_to "退会", "/users/#{@current_user.id}", class: "delete-button", method: :delete, data:{confirm: "本当に退会しますか？"} %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="edit-wrapper">
  <div class="edit-box">
    <p class="edit-box-title">アカウント編集</p>

    <% if @error_message %>
      <p class="error"><%= @error_message %></p>
    <% end %>
    <% if @user.errors.full_messages.any? %>
      <% @user.errors.full_messages.each do |message| %>
        <p class="error"><%= message %></p>
      <% end %>
    <% end %>

    <%= form_with model: @user, url: {controller: 'users', action: 'update_account' } do |f| %>
      <div class="edit-box-form">
        <ul>
          <li>
            <p>メールアドレス</p>
            <%= f.text_field :email, class: "profile-edit-field" %>
          </li>
          <li>
            <p>現在のパスワード</p>
            <%= f.password_field :password, class: "profile-edit-field", placeholder: "現在のパスワードを入力", value: '' %>
          </li>
          <li>
            <p>変更後パスワード（変更する場合のみ入力）</p>
            <%= f.password_field :password_reset, class: "profile-edit-field", value: '' %>
          </li>
          <li>
            <p>パスワード確認用（変更する場合のみ入力）</p>
            <%= f.password_field :password_reset_confirmation, class: "profile-edit-field", value: '' %>
          </li>
        </ul>
        <%= f.submit "更新",class: "edit-submit button" %>
        <%= link_to "戻る" ,"/users/account", class: "edit-button button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="log_in-wrapper">
  <div class="log_in-wrapper-box">
    <p class="log_in-wrapper-text">ログイン</p>

    <% if @error_message %>
      <p class="error"><%= @error_message %></p>
    <% end %>

    <%= form_with url: "/users/log_in" do |f|%>
      <ul class="log_in-wrapper-form">
        <li>
          <p class="require-text">必須</p>
          <%= f.email_field :email, value: @input, class: "log_in-field", :placeholder => "メールアドレス" %>
        </li>
        <li>
          <p class="require-text">必須</p>
          <%= f.password_field :password, class: "log_in-field", :placeholder => "パスワード" %>
        </li>
        <%= f.submit "ログイン",class: "log_in-submit button" %>
      </ul>
    <%end%>
    <%= link_to "新しいアカウントを作成", "/users/sign_up" %>
  </div>
</div>

app/views/users/top.html.erb
<div class="top-wrapper">
  <div class="top-wrapper-content">
    <h1>HotelReserveで泊まったり<br>泊まられたりしよう</h1>
    <p>エリア</p>
    <%= form_with url: search_area_path, method: :get do |f|%>
      <%= f.text_field "search",class: "top-wrapper-form top-wrapper-form-field", :placeholder => "東京" %>
      <%= f.submit "探す",class: "top-wrapper-form top-wrapper-form-submit" %>
    <% end %>
  </div>
</div>

<div class="recommended-wrapper">
  <h1>おすすめのエリア</h1>
  <div class="recommended-wrapper-boxes">
    <%= link_to search_keyword_path(search: "東京"), class: "links" do %>
      <div class="recommended-wrapper-box">
        <%= image_tag "tokyo.jpg", class: "recommended-wrapper-image" %>
        <p class="recommended-wrapper-text">東京</p>
      </div>
    <% end %>

    <%= link_to search_keyword_path(search: "大阪"), class: "links" do %>
      <div class="recommended-wrapper-box">
        <%= image_tag "osaka.jpg", class: "recommended-wrapper-image" %>
        <p class="recommended-wrapper-text">大阪</p>
      </div>
    <% end %>

    <%= link_to search_keyword_path(search: "金沢"), class: "links" do %>
      <div class="recommended-wrapper-box">
        <%= image_tag "kanazawa.jpg", class: "recommended-wrapper-image" %>
        <p class="recommended-wrapper-text">金沢</p>
      </div>
    <% end %>

    <%= link_to search_keyword_path(search: "沖縄"), class: "links" do %>
      <div class="recommended-wrapper-box">
        <%= image_tag "okinawa.jpg", class: "recommended-wrapper-image" %>
        <p class="recommended-wrapper-text">沖縄</p>
      </div>
    <% end %>
  </div>
</div>